server:
  port: 8080

# 关闭运行日志图标
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
#    username: root
#    password: 123456

    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://bi-clickhouse13.gitv.we:8123/default?socket_timeout=600000,jdbc:clickhouse://bi-clickhouse14.gitv.we:8123/default?socket_timeout=600000
    username: developer
    password: cqKUkv!#IAvAOkbt(


person:
  lastName: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12
